package JavaThreadClass; // project made in eclipse

public class BasicThreadPT2 extends Thread {// public class created, inheritance used to extend from 'Thread'
	public static int amount = 0; // set public static int amount to 0

	public static void main(String[] args) {// reads, runs and executes
		
	// created object of class, object named 'newBasicThread'
		BasicThreadPT2 newBasicThread = new BasicThreadPT2();
		
		newBasicThread.start(); // starts execution of Thread
		
		while(newBasicThread.isAlive()) { //while loop is created getting object to call onto 
//the ".isAlive()" method, this checks if thread has finished running before doing anything else
			
			System.out.println("Calculating..."); // Displaying text
		}
		System.out.println("Currency: " + amount); // display text & amount in number increments by 1
		amount++;
		System.out.println("Currency: " + amount); // display text & amount in number
	}
	
	public void run() {
	amount++; // increments by 1
	}
}
// result:
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Calculating...
//Currency: 1
//Currency: 2